{
 "title": "Kafka Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_active_controller_count"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_offline_partitions_count"
    }
   ]
  },
  {
   "title": "Number of Under-replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_under_replicated_partitions"
    }
   ]
  },
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Invalid Auths / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Invalid Auths" }
   ],
   "targets": [
    {
     "expr": "kafka_server_zookeeper_auth_failure_per_sec"
    }
   ]
  },
  {
   "title": "Successful Auths / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Successful Auths" }
   ],
   "targets": [
    {
     "expr": "kafka_server_zookeeper_sasl_auth_per_sec"
    }
   ]
  },
  { "title": "Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Bytes In / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_total_bytes_in_per_sec"
    }
   ]
  },
  {
   "title": "Bytes Out / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_total_bytes_out_per_sec"
    }
   ]
  },
  {
   "title": "Messages In / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "kafka_server_messages_in_per_sec"
    }
   ]
  }
 ]
}